### ISSUE TITLE
Bounds on particle position

### ISSUE THREAD

**Issue by loicspace** [ozanarkancan/ParticleSwarmOptimization.jl#1]
Hi,

I'm really interested in using your package for spacecraft trajectory optimization applications. For such an application, the variables are orbital elements (semimajor axis, eccentricity, ...) and each has a physical range. However, if I understand right, with your implementation, one can only set a single upper (h) and lower (l) bound on the particle position while in my application I would need to define a specific upper and lower bound for each dimension of the problem (semimajor axis, eccentricity, ...) 
Is it of interest to you to generalize the implementation to allow such upper and lower bounds? Essentially, it comes to defining l and h as an array, say Array{Float64, dim} rather than Float64?

Thank you,
Loic

**Comment by ozanarkancan** [comment]
Hi,

I am glad to see my package could help you for your project. I updated the package to allow different bounds for each dimension of the position vector. Currently, this option works only on CPU. Will you use the package on GPUs?

Example:
examples/hosaki.jl

**Comment by loicspace** [comment]
Hi,

Wow, thanks, that's very helpful and impressive responsiveness. I do plan
on using the GPU eventually but I planned on using the CPU initially to
test, validate, and produce initial results.
Thanks again!

Loic

**Comment by loicspace** [comment]
Hi,

I noticed that for the initialization of the particles, a uniform random distribution is used. However, if I read that right, a unique distribution is used for all dimensions of the problem such that the bounds for the distribution are taken as the minimum and maximum of the array of lower and upper bounds for the entire set of variables rather than creating individual distribution for each variable with the appropriate bounds. This can cause issues for scenarios where some variables have a specific domain, for instance, in my application the code deals with eccentricity that must belong to [0,1] while other variables are angles and can vary from 0 to 360. Then, an eccentricity value out of the bounds [0,1] causes math functions error, e.g. trigonometric functions that operate on a specific domain. I can add variable checks in my code to enforce bounds but it would be more efficient and elegant to have that taken care of in the initialization of the particles, in "uniform" in "Particle.jl" I believe.

Thanks,
Loic

**Comment by ozanarkancan** [comment]
Hi,

It is fixed.

Thanks.

**Comment by loicspace** [comment]
Outstanding.
Thank you.
